# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f00500420346025d6d6406f4663f6e3d2afa02668b4911f8e227f4331421a9508e196f52321d04758990b579202af476e63d826096ed53feb8d32bf6b9267be

test:
  secret_key_base: 08ce897e097c45845b9078af33c678ce4e0b8483055bb15eec89f2ca31733bb7f1c4a7d1bdc8708f6fefd19e926b402d90e5fae84f2d951077f41db6719330cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
